// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package di

import (
	"context"
)

// Injectors from wire.go:

func NewApp(ctx context.Context) (*App, func(), error) {
	db := provideDB()
	userHandler := provideUserHandler(ctx, db)
	app := &App{
		UserHandler: userHandler,
		Db:          db,
	}
	return app, func() {
	}, nil
}
