// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package di

import (
	"context"
)

// Injectors from wire.go:

func NewApp(ctx context.Context) (*App, func(), error) {
	db := provideDB()
	contentHandler := provideContentHandler(ctx, db)
	app := &App{
		ContentHandler: contentHandler,
		Db:             db,
	}
	return app, func() {
	}, nil
}
