CREATE TABLE IF NOT EXISTS users (
    id INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    display_name VARCHAR(128) NOT NULL,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
